# Uncomment the next line to define a global platform for your project
# platform :ios, '13.0'

target 'RxSwiftArchitecture' do
  # Comment the next line if you don't want to use dynamic frameworks
  use_frameworks!

  # Pods for RxSwiftArchitecture
   pod 'RxSwift'
   pod 'RxCocoa'
   pod 'RxGesture'

  target 'RxSwiftArchitectureTests' do
    inherit! :search_paths
    # Pods for testing
  end

  target 'RxSwiftArchitectureUITests' do
    # Pods for testing
  end

end
